list <- read.csv("C:/Clusters/SampleSouthEastTravel.csv", header= TRUE)
summary(list)
shapiro.test(list$Bus_Minibus_Coach_2011)
shapiro.test(list$Car_Driver_2011)


library(moments)
library(nortest)
library(e1071)
qqnorm(list$Bus_Minibus_Coach_2011); qqline(list$Bus_Minibus_Coach_2011)
qqnorm(list$Car_Driver_2011); qqline(list$Car_Driver_2011)
hist(list$Bus_Minibus_Coach_2011)
skewness(list$Bus_Minibus_Coach_2011)
skewness(list$Car_Driver_2011)
hist(list$Car_Driver_2011)
kurtosis(list$Bus_Minibus_Coach_2011)
kurtosis(list$Car_Driver_2011)
probplot(list$Bus_Minibus_Coach_2011, qdist=qnorm)
probplot(list$Car_Driver_2011, qdist=qnorm)
listFit <- lm( Car_Driver_2011 ~ Bus_Minibus_Coach_2011 , data=list )
plot(listFit)
qqnorm(listFit.stdRes,ylab="Standardized Residuals",xlab="Normal Scores", main="Normality Plot", col="red")
qqline(listFit.stdRes)
kruskal.test( Car_Driver_2011 ~ Bus_Minibus_Coach_2011, data = list) 
